[package]
name = "sir-bench"
version = "0.1.0"
edition = "2024"

[dependencies]
approx = "0.5.1"
clap = { version = "4.5.46", features = ["derive"] }
indexmap = "2.11.0"
ixa = "0.3.1"
plotly = "0.13.5"
rand = "0.9"
rand_distr = "0.5.1"
serde = "1.0.219"
statrs = "0.18.0"
