name: Test and check formatting, lints

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install just
        uses: extractions/setup-just@v3

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/cache
            ~/.cargo/registry
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Run lint, formatting checks
        run: just check

      - name: Run tests
        run: just test

      - name: Check that the models don't die out
        run: just run sir --check-attack-rate && just run large --check-attack-rate

